version: 0.2

phases:
  install:
    commands:
        - curl https://bootstrap.pypa.io/pip/3.4/get-pip.py -o get-pip.py
        - python3 get-pip.py --user --force-reinstall
        - python3 -m pip install Flask
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python3 test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
